### ISSUE TITLE
Not Working after upgrading to April-2020

### ISSUE THREAD

**Issue by sujithgudipudi** [levi-turner/60f3cacb-c4ee-47d3-8a40-9f23530c0267#1]
HI Jesse,
We have upgraded QlikSense from Feb-2019 to April-2020 and then after "NotificationAdderListener" isn't working. Can you please help in fixing this.

**Comment by levi-turner** [comment]
I am not seeing issues with my June 2020 installation (around Feb 2020 as I recall we did switch Node versions). The expectation from our side is that every upgrade will require re-applying the `services.conf` setting since this file is modified by the installer on upgrade / patch / etc.

Does the script run manually?

**Comment by sujithgudipudi** [comment]
Thanks for your quick response. I was  trying to restart the engine server on proxy service and that didn't update the csv file. However when i restarted the engine service on engine then the file got updated. Thanks for your quick response.
